language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

before_install:
    - env
    - uname -a

install:
    # Show current environment
    - python -V
    - pip --version

    # Install Coveralls
    - pip install coveralls

script:
    # Unit Test
    - coverage run -p setup.py test

after_success:
    - coverage combine
    - coveralls
