name: "Test"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install -v .

      - name: Show environment
        run: |
          env
          python -V
          pip freeze

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          python -m pytest -rfEX --showlocals --cov --cov-branch atwiki
          atwiki-dump --help

      - name: Upload Coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
